---
- hosts: mac
  vars:
    taps:
      - homebrew/cask
      - homebrew/cask-fonts
    casks:
      # Window manager
      - rectangle
      # RDM allows switching between screen resolution easily.
      - avibrazil-rdm
      # Popular browsers
      - brave-browser
      - firefox
      - google-chrome
      # GUI archiver
      - keka
      # image optimization tools
      - imageoptim
      - imagealpha
      - spotify
      - spotify-now-playing
      # Clipboard manager
      - maccy
      # Drawing app
      - krita
      # Screen capture
      - kap
      - keybase

  tasks:
    - name: Register taps
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: "{{ taps }}"

    - name: Install casks
      community.general.homebrew_cask:
        name: "{{ casks }}"
        state: present
        accept_external_apps: true
