---
- hosts: mac
  gather_facts: yes

  vars:
    casks:
      # GPU accelerated terminal
      - alacritty
      # Good monospace fonts for code
      - homebrew/cask-fonts/font-go-mono-nerd-font
      - homebrew/cask-fonts/font-iosevka-slab
      - homebrew/cask-fonts/font-juliamono
      # Merge tool for git
      - meld
      - postman
      # - slack
      # - virtualbox
      # - virtualbox-extension-pack
      - visual-studio-code
      - jetbrains-toolbox
      - postman

    terminal_font:
      family: "Iosevka Fixed Slab"
      size: 18

    vscode_font:
      family: "Iosevka Slab Light"
      size: 18
      ligatures:
        - zero
        - ss01
        - ss06
        - ss08
        # - "'calt' on"
    vscode_settings:
      "editor.formatOnSave": true

  tasks:
    - name: Install development casks
      homebrew_cask:
        name: "{{ casks }}"
        state: present
        accept_external_apps: true

    - name: Deploy Alacritty configuration
      block:
        - name: Create alacritty config directory
          file:
            path: "~/.config/alacritty"
            state: directory
            mode: u=rwx
        - name: Deploy alacritty config
          template:
            src: alacritty.yml.j2
            dest: "~/.config/alacritty/alacritty.yml"

    - name: Configure VSCode Font settings
      vars:
        settings_path: "~/Library/Application Support/Code/User/settings.json"
        settings: {}
      block:
        - name: Read existing settings
          slurp:
            src: "{{ settings_path }}"
          register: old_settings
          ignore_errors: yes

        - set_fact:
            settings: "{{ old_settings.content | b64decode | regex_replace('\\/\\/.*\\n', ' ')  | from_json }}"
          when: old_settings.content is defined

        - name: Merge font settings
          vars:
            new_values:
              "editor.fontFamily": "{{ vscode_font.family }}"
              "editor.fontLigatures": "{{ vscode_font.ligatures  | map('quote') | join(',') }}"
              "editor.fontSize": "{{ vscode_font.size  | int }}"
          set_fact:
            new_settings: "{{ settings | combine(new_values) | combine(vscode_settings) }}"

        - name: Write updated settings back
          copy:
            content: "{{ new_settings | to_nice_json(indent=2) }}"
            dest: "{{ settings_path }}"
