---
- hosts: mac
  gather_facts: yes

- import_playbook: base.yml
- import_playbook: vim.yml
- import_playbook: base-gui.yml
- import_playbook: mac-settings.yml
- import_playbook: development.yml
- import_playbook: node.yml
- import_playbook: development-gui.yml

- hosts: mac
  gather_facts: yes
  tasks:
    - name: Notify about IDEs
      shell: |
        echo '\n
        == Done ==
        \n\n
        ⚠️  Unfortunately you have to install the Jetbrains IDEs manually  ⚠️
        ⚠️  from toolbox, since there is no command line interface.        ⚠️'
